### ISSUE TITLE
Why not changing a name?

### ISSUE THREAD

**Issue by Piter432** [InternalError503/restart-my-chrome#2]
Why not changing a name of this extension to “Clear my Chrome” for example? This extension already expands the options to clear some things from Chrome, like only cache from websites clearing instead clearing both caches from websites and Chrome's apps (if clearing caches Chrome's option does that, what I wrote).

**Comment by InternalError503** [comment]
Hi @Piter432 

Unfortunately due to changed by google, Restart my chrome is dead, As for your suggestion we have already built an extension from its ashes called [Forget It](https://github.com/InternalError503/forget-it) also available in the [google store](https://chrome.google.com/webstore/detail/forget-it/nlkcdcegdeibofhgkiodigcnidlbgafe?utm_source=git-repo).

The reason why we did not use the word chrome in its name as due to googles policies, So we took a good deal of inspiration from Firefox forget feature in the new extension.

**Comment by Piter432** [comment]
Ah, I forget that stupid Google's policy :/ But anyway, thank you for the information. Better for me (and probably you as well :P), because I can translate “Forget It” :)
